### ISSUE TITLE
Make TTS driver and speed adjustable from settings

### ISSUE THREAD

**Issue by fcnjd** [scheibler/WalkersGuide-Android#5]
Hi,
while navigating the UI, both the screenreader and Walkersguide will call the TTS service. If they're using the same (which at the moment is the only possible option), they may get in conflict. Example: The user navigates, while Talkback focuses on the decreasing distance to the next route point. Walkersguide announcements can thereby get ommitted.
Solutions: TTS driver can be selected from the app settings. Therefore, if a user has more than one driver installed (which is recommended for that use case), they don't get in the way of each other. For higher flexibility, speed should also be changeable.

**Comment by scheibler** [comment]
> TTS driver can be selected from the app settings. Therefore, if a user has more than one
> driver installed (which is recommended for that use case), they don't get in the way of each other.

That's not possible. Talkback always takes presents over anything an app pushes to the tts engine,
regardless if you use the same tts engine or not - At least as long as you move around with your
finger and do something.

And that's a good thing too because otherwise you would end up with two tts overlapping each other
and you couldn't control the one from the app.

Yes you might miss a navigation clue from the app but since you're currently using the app anyway
that should not be such an issue at all.

> For higher flexibility, speed should also be changeable.

Yes, I could implement that but the idea was that WalkersGuide uses the same tts settings for
announcements as Talkback does. Therefore the speed and all other parameters already should be set to the
users liking.

**Comment by fcnjd** [comment]
OK, now I got your idea of using the same TTS engine and preferences as Talkback does. However, maybe we could reconsider this:
Talkback not necessarily only interrupts speech while using the app. If focus is on an auto-updating element (such as a distance indicator), or get's placed there by accident, Talkback takes precedence. Another case: Notifications of other apps make Talkback speak, grabbing the TTS away from Walkersguide. And once a clue is spoken, it won't be repeated. From my perspective, those interruptions aren't that unlikely. That's why the Lazarillo app explicitly asks you to choose a second TTS (if you have one) to prevent Talkback getting in the way - and if you don't have one, they manage to repeat a voice message if it was interrupted. So it is indeed possible. Please don't get me wrong, I prefer using Walkersguide because of many reasons, including UI and route navigation - but in this case I think they did a good way of implementing the TTS.

**Comment by fcnjd** [comment]
Another point: Talkbac can't be kept from speaking since the display has to keep active for the TTS to play. However it can be interrupted and resumed when needed, by using the 2 finger gesture or getting close to the prximity. The navigation clues don't have those options, so they should take priority. I can try to look into the code and add the settings for variable TTS driver and speed - in the hope that I'll understand the structure.

**Comment by scheibler** [comment]
Please see #6 for updates.

**Comment by scheibler** [comment]
See release v3.2.0
